kind: Service
apiVersion: v1
metadata:
  name: micro1
spec:
  selector:
    app: micro1
  ports:
  - protocol: TCP
    port: 8080
    name: micro1app
    nodePort: 30002
  - protocol: TCP
    port: 9081
    name: micro1actuator
    nodePort: 30003
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro1
spec:
  selector:
      matchLabels:
        app: micro1
  replicas: 1
  template:
    metadata:
      labels:
        app: micro1
    spec:
      containers:
        - name: websocket1
          image: registry.gitlab.com/amarinkovic/micro1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: micro1app
            - containerPort: 9081
              name: micro1actuator
      imagePullSecrets: 
        - name: gitlab-reg-cred
            