management:
    metrics:
        export:
          prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - metrics
                    - info
                    - health
spring.output.ansi.enabled: ALWAYS
