
management:
    metrics:
        export:
          prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - metrics
                    - info
                    - health

spring.output.ansi.enabled: ALWAYS

server.port: 8443
server.port-http: 8080

security.require-ssl: true
server.ssl.key-store-type: PKCS12
server.ssl.key-store: "classpath:keystore.p12"
server.ssl.key-store-password: micro1
server.ssl.key-alias: micro1