
management:
    metrics:
        export:
          prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - metrics
                    - info
                    - health

spring.output.ansi.enabled: ALWAYS

server:
    port: 8443
    port-http: 8080
    ssl:
      key-store-type: PKCS12
      key-store: "classpath:keystore.p12"
      key-store-password: micro1
      key-alias: micro1

security.require-ssl: true
