management:
    server:
        port: 9081
    metrics:
        export:
          prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include:
                    - prometheus
                    - metrics
                    - info
                    - health